apiVersion: v1
kind: PersistentVolume
metadata:
  name: standard-pv
  namespace: default
spec: 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/kubernetes/data"